import React from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  Linking,
} from 'react-native';

const PRIVACY_URL =
  'https://sites.google.com/view/privacy-policy-of-converter/inicio';

export default function PrivacyPolicyScreen() {
  const openPrivacyPolicy = () => {
    Linking.openURL(PRIVACY_URL);
  };

  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Privacy Policy Summary</Text>
      <Text style={styles.updated}>Last updated: March 12, 2026</Text>

      <Text style={styles.paragraph}>
        Converter Image to PDF is designed to convert images to PDF, convert PDFs to images,
        merge PDF files, preview documents and export them from the device. Core conversions
        are performed locally on the device.
      </Text>

      <Text style={styles.sectionTitle}>How the app uses permissions</Text>
      <Text style={styles.paragraph}>
        Camera access is requested only when the user taps the option to take a photo.
        The app does not request camera access when the user only selects existing images.
      </Text>
      <Text style={styles.paragraph}>
        The app is configured to avoid broad photo-library permissions on Android. Users select
        files and images through system pickers or export files to a folder they choose.
      </Text>

      <Text style={styles.sectionTitle}>Local processing and storage</Text>
      <Text style={styles.paragraph}>
        Image-to-PDF, PDF merge and most document processing happen locally on the device.
        Generated files may be stored temporarily in app storage and may also be exported by the
        user to a chosen folder or shared manually.
      </Text>

      <Text style={styles.sectionTitle}>Ads and analytics-related data</Text>
      <Text style={styles.paragraph}>
        This app uses Google AdMob. Google and its partners may process identifiers, IP address,
        device and diagnostic information, and ad interaction data according to Google's policies
        in order to serve, measure and protect ads.
      </Text>

      <Text style={styles.sectionTitle}>Subscriptions</Text>
      <Text style={styles.paragraph}>
        Premium purchases are handled by Google Play Billing. Payment card information is not
        collected or stored directly by the developer through the app.
      </Text>

      <Text style={styles.sectionTitle}>Data retention and deletion</Text>
      <Text style={styles.paragraph}>
        Files generated by the app remain on the device unless the user deletes them. Local
        history entries can be removed by the user from the app. Data processed by third parties
        such as Google AdMob or Google Play Billing is subject to those providers' own retention
        practices and policies.
      </Text>

      <Text style={styles.sectionTitle}>Third parties</Text>
      <Text style={styles.paragraph}>
        The app may rely on Google Play services, Google AdMob and Google Play Billing. Their
        handling of data is governed by their own terms and privacy notices.
      </Text>

      <Text style={styles.sectionTitle}>Full public privacy policy</Text>
      <Text style={styles.paragraph}>
        Read the full public privacy policy here:
      </Text>
      <Text style={styles.link} onPress={openPrivacyPolicy}>
        https://sites.google.com/view/privacy-policy-of-converter/inicio
      </Text>

      <Text style={styles.sectionTitle}>Contact</Text>
      <Text style={styles.email}>amedastudios@gmail.com</Text>

      <View style={{ height: 40 }} />
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#ffffff',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  updated: {
    fontSize: 13,
    color: '#666',
    marginBottom: 18,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginTop: 20,
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 10,
    color: '#444',
  },
  link: {
    fontSize: 15,
    color: '#2e78ff',
    marginBottom: 10,
  },
  email: {
    fontSize: 15,
    fontWeight: '500',
  },
});
